name: thesis
channels:
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.0.2u=h7b6447c_0
  - pip=20.2.4=py37_0
  - python=3.7.0=h6e4f718_3
  - readline=7.0=h7b6447c_5
  - setuptools=50.3.0=py37hb0f4dca_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
      - absl-py==1.0.0
      - astunparse==1.6.3
      - cached-property==1.5.2
      - cachetools==5.0.0
      - chainer==2.0.2
      - charset-normalizer==2.0.11
      - cupy==8.3.0
      - cycler==0.11.0
      - decord==0.6.0
      - dlib==19.23.0
      - fastrlock==0.8
      - filelock==3.4.2
      - filterpy==1.4.5
      - flatbuffers==2.0
      - fonttools==4.29.1
      - gast==0.5.3
      - google-auth==2.6.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.43.0
      - h5py==3.6.0
      - idna==3.3
      - importlib-metadata==4.11.0
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.2
      - libclang==13.0.0
      - llvmlite==0.38.0
      - markdown==3.3.6
      - matplotlib==3.5.1
      - mock==4.0.3
      - mtcnn==0.1.1
      - nose==1.3.7
      - numba==0.55.1
      - numpy==1.21.5
      - oauthlib==3.2.0
      - opencv-python==4.5.5.62
      - opt-einsum==3.3.0
      - packaging==21.3
      - pillow==9.0.1
      - protobuf==3.19.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyparsing==3.0.7
      - python-dateutil==2.8.2
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - rsa==4.8
      - scipy==1.5.2
      - six==1.16.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.0
      - tensorflow-io-gcs-filesystem==0.24.0
      - termcolor==1.1.0
      - tf-estimator-nightly==2.8.0.dev2021122109
      - timm==0.4.5
      - torch==1.10.2
      - torchvision==0.11.3
      - typing-extensions==4.0.1
      - urllib3==1.26.8
      - werkzeug==2.0.3
      - wrapt==1.13.3
      - zipp==3.7.0
prefix: /home/tuanld/miniconda3/envs/thesis
